apiVersion: batch/v1
kind: Job
metadata:
  name: infinigen-generator
  labels:
    name: infinigen-generator
spec:
  completions: 32
  parallelism: 32
  completionMode: Indexed
  template:
    spec:
      containers:
        - name: infinigen-generator
          image: saadam1n/infinigen-generator:latest
          command: ["/bin/sh", "-c", "apt update && apt install cmake g++ libgconf-2-4 libgles2-mesa-dev libglew-dev libglfw3-dev libglm-dev libxi6 sudo unzip vim zlib1g-dev libxkbcommon-x11-0 libsm6 -y && conda run -n infinigen pip install jinja2 && conda run --no-capture-output -n infinigen python -u -m infinigen.datagen.manage_jobs --output_folder /mnt/infinigen_output/job-$(JOB_COMPLETION_INDEX)/ --overwrite --num_scenes 32 --pipeline_configs local_256GB.gin denoise_gen.gin indoor_background_configs.gin --configs singleroom --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' LocalScheduleHandler.use_gpu=False --overrides compose_indoors.terrain_enabled=False compose_indoors.restrict_single_supported_roomtype=True AnimPolicyRandomWalkLookaround.speed=0.5 AnimPolicyRandomWalkLookaround.step_range=0.5 compose_indoors.animate_cameras_enabled=True"]
          resources:
            requests:
              memory: "256Gi"
              cpu: "32"
            limits:
              memory: "256Gi"
              cpu: "32"
          volumeMounts:
          - mountPath: /mnt/infinigen_output/
            name: infinigen-pvc
      volumes:
      - name: infinigen-pvc
        persistentVolumeClaim:
          claimName: infinigen-pvc
      restartPolicy: Never
